
    
Form the 2-D array (without typing it in explicitly):

<p>[[1,  6, 11],</p>
 <p>[2,  7, 12],</p>
 <p>[3,  8, 13],</p>
 <p>[4,  9, 14],</p>
 <p>[5, 10, 15]]</p>
 
and generate a new array containing its 2nd and 4th rows.



In [17]:
import numpy as np

In [18]:
#Una forma de generar el 2D-array
np.array([np.arange(1,16,5), np.arange(2, 17, 5), np.arange (3, 18, 5), np.arange (4, 19, 5), np.arange (5, 20, 5)])


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [59]:
#Otra forma de generar el 2D-array
a=np.arange(1,16).reshape(3,5)
a
b=a.transpose()
b

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [65]:
#Array con la segunda fila
c=b[1]
c

array([ 2,  7, 12])

In [66]:
#Array con la cuarta fila
d=b[3]
d

array([ 4,  9, 14])

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

<ul style="list-style-type:circle">
    <li>Use <i>abs</i> and <i>argsort</i> to find the column <i>j</i> closest for each row.</li>
    <li>Use fancy indexing to extract the numbers. (Hint: <i>a[i,j]</i> - the array <i>i</i> must contain the row numbers corresponding to stuff in <i>j</i>.)</li>
    </ul>


In [67]:
#Array 10x3 de aleatorios entre 0 y 1.
e = np.random.rand(10,3)
e

array([[ 0.13876252,  0.87321632,  0.82444421],
       [ 0.47018027,  0.83898355,  0.8915623 ],
       [ 0.86587714,  0.69079263,  0.86337202],
       [ 0.82467219,  0.60565125,  0.90998286],
       [ 0.22637836,  0.24885196,  0.32986353],
       [ 0.81671484,  0.0957946 ,  0.98861672],
       [ 0.64441144,  0.4284999 ,  0.9343604 ],
       [ 0.51233757,  0.60578681,  0.71693099],
       [ 0.64206477,  0.6360862 ,  0.44919194],
       [ 0.74906801,  0.06063384,  0.2147583 ]])

In [73]:
#Creo otro array que resta 0.5 al anterior, en valor absoluto para calcular la distancia entre los elementos del array y 0.5.
f = np.abs(e - 0.5)
f

array([[ 0.36123748,  0.37321632,  0.32444421],
       [ 0.02981973,  0.33898355,  0.3915623 ],
       [ 0.36587714,  0.19079263,  0.36337202],
       [ 0.32467219,  0.10565125,  0.40998286],
       [ 0.27362164,  0.25114804,  0.17013647],
       [ 0.31671484,  0.4042054 ,  0.48861672],
       [ 0.14441144,  0.0715001 ,  0.4343604 ],
       [ 0.01233757,  0.10578681,  0.21693099],
       [ 0.14206477,  0.1360862 ,  0.05080806],
       [ 0.24906801,  0.43936616,  0.2852417 ]])

In [81]:
#argsort nos dará para cada fila el orden en que se sitúan los elementos respecto a 0.5.
g = np.argsort(f)
g

array([[2, 0, 1],
       [0, 1, 2],
       [1, 2, 0],
       [1, 0, 2],
       [2, 1, 0],
       [0, 1, 2],
       [1, 0, 2],
       [0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [83]:
#Seleccionamos la primera columna, que indica qué elemento de cada fila se encuentra más proximo a 0.5.
h = g[:,0]
h

array([2, 0, 1, 1, 2, 0, 1, 0, 2, 0])

In [85]:
#Creo un nuevo array i que es el array inicial h ordenado en función del array de índices h
i = e[np.arange(e.shape[0]),h]
i

array([ 0.82444421,  0.47018027,  0.69079263,  0.60565125,  0.32986353,
        0.81671484,  0.4284999 ,  0.51233757,  0.44919194,  0.74906801])



The data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

Computes and print, based on the data in populations.txt (use loadtxt to read the file)...

    1.The mean and std of the populations of each species for the years in the period.
    2.Which year each species had the largest population.
    3.Which species has the largest population for each year. (Hint: argsort & fancy indexing of np.array(['H', 'L', 'C']))
    4.Which years any of the populations is above 50000. (Hint: comparisons and np.any)
    5.The top 2 years for each species when they had the lowest populations. (Hint: argsort, fancy indexing)
    6.Compare (plot) the change in hare population (see help(np.gradient)) and the number of lynxes. Check correlation (see help(np.corrcoef)).

... all without for-loops.


In [ ]:
http://www.scipy-lectures.org/_downloads/populations.txt

In [77]:
data = np.loadtxt('data/populations.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'data/populations.txt'

In [101]:
a = np.arange(7,18,1)
a



array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [104]:
indices = np.array([[3, 4], [9, 7]])
b=a[indices]
b

array([[10, 11],
       [16, 14]])